### ISSUE TITLE
Users.find('some_id') == nil

### ISSUE THREAD

**Issue by danlo** [bnorton/tap_if#3]
Greetings,

I came across tap_if, and I ran into an interesting problem.

```
User.find('some_id').tap_if {
}
```

The issue, is that the above user does not exist and .tap_if is not defined for null, I thought about re-opening NilClass and adding .tap_if to NilClass, kind of quesy, I mean... nil.tap_if(:is_admin?) {  } 

How did you address this issue in your own coding?

Thank you!

BTW: https://rubygems.org/gems/tap-if/versions/0.5.0  The "homepage" link in the bottom right points the wrong github repository.

**Comment by bnorton** [comment]
@danlo I would welcome this being added to `NilClass` -- will you open a PR for this (or I can add it in)

**Comment by hosh** [comment]
Using Ruby 2.4's `&.` syntax:

```
User.find('some_id')&.tap { }
```

**Comment by danlo** [comment]
A co-worker pointed this out:.

User.find('some bad id')&.tap{  } returns nil.  Not sure you still want to add this feature?
 "&." appears in ruby 2.3.0, I can add a note to the documentation with a PR?
